//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OstoslistaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostoslista
    {
        public int ostoid { get; set; }
        public string tuotteennimi { get; set; }
        public string määrä { get; set; }
        public Nullable<bool> korissa { get; set; }
    }
}
